nv-morpheus/MRC

- python/CMakeLists.txt
> Set Python3_FIND_STRATEGY and disable the old python policy

- ci/conda/environments/dev_env.yml
- ci/conda/recipes/libsrf/meta.yaml
> Add pybind11-stubgen to the conda build

- include/srf/options/placement.hpp
- src/internal/system/partitions.cpp
- src/tests/test_partitions.cpp
Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

- src/internal/executor/executor.cpp
> Fix for pipelines beginning before start is called

- python/srf/_pysrf/src/operators.cpp
This is a hotfix to close #116. This PR reverts the implementation back to the one that does not use `concat_map` and `iterate`. This also ensures all `on_error` and `on_completed` are forwarded.
> Fix `flatten()` Operator With Infinite Sources

- CHANGELOG.md
- python/srf/_pysrf/src/operators.cpp
> [RELEASE] SRF v22.06.01 Hotfix

- .github/workflows/add_to_project.yml
Automatically add any new issue or PR created in this repo to the tracking project using GitHub Actions.
> Action to Add Issues/PRs to Project

- python/srf/_pysrf/include/pysrf/port_builders.hpp
Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.09` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.08 to branch-22.09 [skip gpuci]

- ci/scripts/cpp_checks.sh
- ci/scripts/python_checks.sh
> Add missing checks for YAPF_RETVAL & PRAGMA_CHECK_RETVAL in CI

- CONTRIBUTING.md
Fixes #150
Setting bin PATH alone did not work in my testing.
> CONTRIBUTING updates for CUDA

- CHANGELOG.md
- CMakeLists.txt
- CONTRIBUTING.md
- ci/scripts/cpp_checks.sh
- ci/scripts/jenkins/checks.sh
- ci/scripts/python_checks.sh
- cmake/deps/Configure_hwloc.cmake
- cmake/deps/Configure_ucx.cmake
- cmake/import_rapids_cmake.cmake
- docs/quickstart/CMakeLists.txt
- docs/quickstart/environment_cpp.yml
- protos/CMakeLists.txt
- tools/nvrpc/tests/CMakeLists.txt
Only critical/hotfix level issues should be merged into `branch-22.09` until release (merging of this PR).
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-22.09` into main for the release
> [RELEASE] SRF v22.09

- python/srf/_pysrf/src/segment.cpp
Fixes #181
morpheus issue [#330](https://github.com/nv-morpheus/Morpheus/issues/330)
> Emit the value before incrementing the iterator fixes 

- CMakeLists.txt
- docs/quickstart/CMakeLists.txt
- docs/quickstart/environment_cpp.yml
Some versions in the SRF repo werent properly updated from 22.09 to 22.11
> Updating SRF versions from 22.09 to 22.11

- CONTRIBUTING.md
- README.md
> update clone instructions to include --recurse-submodules

- CMakeLists.txt
- docs/quickstart/CMakeLists.txt
- docs/quickstart/environment_cpp.yml
* Change version to 23.07
* Track branch-23.07 of utilities repo
> bump version to 23.07

- .devcontainer/devcontainer.json
- .devcontainer/init.sh
> add git-lfs and gh config dir

- .gitmodules
- CMakeLists.txt
- ci/release/pr_code_freeze_template.md
- ci/release/update-version.sh
- docs/quickstart/CMakeLists.txt
- docs/quickstart/environment_cpp.yml
This PR contains the changes from running the `ci/release/update-version.sh` script for a new release
> Update Versions for v23.11.00

- ts/control-plane/src/client/client.test.ts
- ts/control-plane/src/proto/google/protobuf/any.ts
- ts/control-plane/src/proto/mrc/protos/architect.ts
- ts/control-plane/src/proto/mrc/protos/architect_state.ts
- ts/control-plane/src/server/store/slices/manifoldInstancesSlice.ts
- ts/control-plane/src/server/store/slices/segmentInstancesSlice.ts
> Fix Manifold<->Segment ref-counting on shutdown

- README.md
- docs/quickstart/python/mrc_qs_python/ex02_reactive_operators/README.md
> Add missing flags to docker command to mount the working dir and set -cap-add=sys_nice

- .github/workflows/pull_request.yml
- Dockerfile
PR updates `rapidsai/ci` references to `rapidsai/ci-conda`.
> update rapidsai/ci to rapidsai/ci-conda

- ci/conda/recipes/libmrc/meta.yaml
> Fix libhwloc & stubgen versions to match dev yaml

- cmake/Configure_UCXX.cmake
- cpp/mrc/CMakeLists.txt
- cpp/mrc/include/mrc/runtime/remote_descriptor.hpp
- cpp/mrc/src/internal/data_plane/data_plane_resources.cpp
- cpp/mrc/src/internal/data_plane/data_plane_resources.hpp
- cpp/mrc/src/public/runtime/remote_descriptor.cpp
- cpp/mrc/src/tests/CMakeLists.txt
- cpp/mrc/src/tests/test_network.cpp
> Track remote descriptors

- mrc.code-workspace
- ts/control-plane/src/client/client.test.ts
- ts/control-plane/src/server/store/slices/manifoldInstancesSlice.ts
- ts/control-plane/src/server/store/slices/segmentInstancesSlice.ts
WIP PR to fix the existing test failures when running the ts/control-plane tests, via `npm run test`.
> [WIP] Fix typescript tests

- ci/check_style.sh
- ci/scripts/github/checks.sh
- docs/quickstart/CMakeLists.txt
- docs/quickstart/python/mrc_qs_python/_version.py
- docs/quickstart/python/mrc_qs_python/ex02_reactive_operators/run.py
> Update CR year

- README.md
> Update minimum requirements

- CHANGELOG.md
- ci/scripts/cpp_checks.sh
- python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
Only critical/hotfix level issues should be merged into `branch-24.03` until release (merging of this PR).
All other development PRs should be retargeted towards the next release branch: `branch-24.06`.
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-24.03` into `main` for the release
> [RELEASE] MRC v24.03.01

- ci/conda/README.md
- cpp/mrc/CMakeLists.txt
- protos/CMakeLists.txt
- python/CMakeLists.txt
- python/mrc/_pymrc/CMakeLists.txt
- python/mrc/_pymrc/tests/CMakeLists.txt
* Resolving merge conflict from #512
> Forward-merge branch-24.10 into branch-25.02

- python/mrc/_pymrc/src/segment.cpp
- python/mrc/core/coro.cpp
> IWYU fixes

- ci/conda/recipes/run_conda_build.sh
- ci/scripts/github/conda.sh
Upstream RAPIDS will eventually be removing boa from the default images. Since they are functionally equivalent, let's adapt.
> Replace `conda-mambabuild` with `conda-build`
