nv-morpheus/MRC

- CMakeLists.txt
The function `rapids_export` uses the variable `RAPIDS_VERSION` to determine the version to export. Since we also have this defined as a cache entry, the function incorrectly exports `RAPIDS_VERSION` in the CMake config file, not `PROJECT_VERSION` as it should according to the docs. This breaks any dependencies that use the SRF conda package.
> Explicitly Specify Version for `rapids_export`

- src/internal/pipeline/controller.cpp
- src/tests/test_pipeline.cpp
Fixes #26 by improving error handling on the `pipeline::Controller` update method
> Improve error handling on pipeline::Controller updates

- CMakeLists.txt
- src/internal/executor/executor.cpp
- src/internal/pipeline/port_graph.cpp
- src/internal/pipeline/port_graph.hpp
- src/tests/test_pipeline.cpp
Fixes #27 by throwing an exception when registering a pipeline with an incomplete or currently invalid port configuration.
> adding PortGraph; validate Pipeline definitions

- ci/conda/environments/dev_env.yml
- ci/conda/recipes/libsrf/meta.yaml
Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

- docs/quickstart/CMakeLists.txt
Fixes #86
If the `python_module_tools` is after `find_package(SRF)`, the build fails. Unclear why, but this fixes it.
> Moving the python_module_tools before the SRF import

- docs/quickstart/README.md
Update of QSG that focuses primarily on:
- Removal of redundant install information provided in the main SRF README
- Improved organization (added TOC and streamlined prose)
- Typo fixes
Targeting branch 22.08 with this, but we should also merge to 22.06
> Refresh and Simplification of QSG README

- src/tests/test_network.cpp
I had put an assumption that the memory required to store UCX remote keys for GPU memory would always be larger than for Host memory.
This assumption is incorrect. The size of buffer for the keys is dependent on which transports are enable, the number of NICs, the number of GPUs and a variety of other runtime variables used to initialize UCX.
I've left a comment in the tests to remind developers and users of that fact.
> fix faulty assumption about remote key sizes

- CONTRIBUTING.md
- README.md
pip install from the build/python dir, not $SRF_HOME/python
Not sure if we need to even mention SRF_PYTHON_INPLACE_BUILD var
@mdemoret-nv
> Adjust contrib instructions for pip install location

- python/srf/_pysrf/include/pysrf/port_builders.hpp
If you create a source or a sink class that derives from `PythonSink`, `PythonSource` or `PythonNode` and the message type does not have a default constructor, you will run into a compilation error. This was due to the fact that the new Port auto registration added in PR #153 tries to compile ingress/egress ports for both `T` and `shared_ptr<T>`.
This PR adds a check to skip compiling a port with `T` if `T` does not have a default constructor.
> Update PortBuilder to Work with Types That Do Not Have a Default Constructor

- CMakeLists.txt
- ci/conda/environments/dev_env.yml
- ci/conda/environments/dev_env_nogcc.yml
- ci/conda/recipes/libsrf/conda_build_config.yaml
- cmake/import_rapids_cmake.cmake
- docs/quickstart/CMakeLists.txt
- docs/quickstart/environment_cpp.yml
Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.09` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.08 to branch-22.09 [skip gpuci]

- CONTRIBUTING.md
Looks like VSCode decided to remove two white-space chars.
fixes #127
> Add documentation on how to build the doxygen docs

- src/tests/test_ucx.cpp
> Registered memory should be released before the UCX Context is destroyed

- .github/workflows/pull_request.yml
- ci/scripts/github/test.sh
As far as I can tell this bug also existed in the Jenkins CI.
> Fix tests so that the proper upstream build is used for the coverage test

- .github/workflows/add_to_project.yml
The current action uses `on: pull_request` but for it to work successfully, it needs to be `on: pull_request_target`
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
> change pull_request to pull_request_target

- src/internal/system/device_info.cpp
- srf.code-workspace
This resolves #124 when using 1 or more standard GPU devices. When multiple GPUs are visible, all MIG devices are ignored.
Issue #205 will enable running on MIG instances under the strict condition that the only visible devices is in MIG mode and that there is only 1 visible MIG instances seen by the calling processes.
Code coverage is expected to decrease because we have no MIG instances in CI.
> Improve NVML + MIG Behavior

- python/srf/_pysrf/src/executor.cpp
- python/srf/tests/CMakeLists.txt
- python/srf/tests/utils.cpp
- python/tests/test_executor.py
Exceptions from both python and C++ were getting printed to the log but not raised in python when using `Executor.join_async()`. This boils down to the fact that `future::wait()` was called instead of `future::get()` which actually rethrows the exception.
Added some tests to check this functionality
> Fix throwing errors from `Executor.join_async()`

- python/srf/tests/sample_modules.cpp
- python/srf/tests/test_edges.cpp
- python/srf/tests/utils.cpp
Forward-merge triggered by push to `branch-22.11` that creates a PR to keep `branch-23.01` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.11 to branch-23.01 [skip gpuci]

- include/srf/segment/builder.hpp
- python/srf/_pysrf/include/pysrf/segment.hpp
- python/srf/_pysrf/src/segment.cpp
- python/srf/core/segment.cpp
- python/tests/test_module_registry.py
- src/public/segment/builder.cpp
Adds missing functionality to allow dynamic modules to forward their configuration to nested children.
Closes #223
>   Adds missing functionality to allow dynamic modules to forward their configuration to nested children.

- .github/CODEOWNERS
- ci/scripts/github/common.sh
The final todo item of the post rename tasks.
Closes #227
> Update codeowners to MRC

- cpp/mrc/src/internal/control_plane/server.cpp
- cpp/mrc/src/internal/control_plane/server.hpp
- cpp/mrc/src/internal/control_plane/server/connection_manager.cpp
- cpp/mrc/src/internal/control_plane/server/connection_manager.hpp
- cpp/mrc/src/internal/resources/manager.cpp
- cpp/mrc/src/tests/test_codable.cpp
Prior to this PR, there was a possible race condition that could be hit by two execution paths where,
- path 1 calls Server::drop_stream which is a yielding call
- path 2 call Server:m_connections->drop_all_streams();
`Server::drop_stream` locks the server's state, but `Server::m_connections` is not protected by that mutex.
Relates to #247
> Fix potential race condition

- cpp/mrc/include/mrc/coroutines/task.hpp
Using gcc, the `if(m_coroutine != nullptr)` could trigger a compilation failure if the coroutine was returning a `std23::expected` with an error message of:
```
error: satisfaction of atomic constraint ... depends on itself
```
Possibly relating to: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99599
Another workaround was to use 
```
if(static_cast<std::coroutine_handle<>>(m_coroutine) != nullptr) {
```
but since `std::coroutine_handle` provides an [`operator bool()`](https://en.cppreference.com/w/cpp/coroutine/coroutine_handle/operator_bool), this is definitely the better way to go as seen by the cppreference.com examples.
> Update Task destructor logic to conform to the standard

- cpp/mrc/include/mrc/core/utils.hpp
Not a bug with our current compiler versions; however, when evaluating gcc 12.2 MRC failed to compile.
> Missing <unordered_map> header; caught by gcc12

- cpp/mrc/include/mrc/coroutines/sync_wait.hpp
- cpp/mrc/include/mrc/coroutines/task.hpp
- cpp/mrc/include/mrc/coroutines/when_all.hpp
- cpp/mrc/tests/coroutines/test_task.cpp
This update allows the Task to transfer ownership of the coroutine handle to the `awaiter` returned by the Task's `operator co_await()` method.
Without this update [the linked test would fail on this line](https://github.com/nv-morpheus/MRC/compare/branch-23.01...ryanolson:task_lifecycle?expand=1#diff-abd2fa1b390dadc99ee7076e518e5ba9029bb0618c908af2ba54134c519f7277R135), because the Task is created in the Awaitable's `operator co_await()` method would not transfer ownership of the coroutines handle to the awaitable, so the Task's destructor would destroy the coroutine who's awaited the caller is awaiting on.
> Improved Task Lifecycle

- cmake/dependencies.cmake
Required to fix a breaking change in https://github.com/nv-morpheus/utilities/pull/5
> rename morpheus_utils_configure_boost_* to use new utilities naming

- .github/workflows/pull_request.yml
- ci/conda/recipes/run_conda_build.sh
- ci/scripts/github/conda.sh
- python/mrc/_pymrc/src/utilities/function_wrappers.cpp
- python/tests/test_node.py
If you used `functools.partial` with any operator function, it would incorrectly thing you wanted to unpack tuples into arguments. This improves on the function signature handling to support using partial functions.
Also includes fixes to the conda build.
> Fix function wrappers with `functools.partial`

- cmake/dependencies.cmake
TL Expected, while not used, is still in the dependency list and this breaks conda packages.
> Removing TL Expected

- cpp/mrc/include/mrc/node/sink_channel_owner.hpp
- cpp/mrc/include/mrc/node/sink_properties.hpp
- cpp/mrc/include/mrc/node/source_channel_owner.hpp
- cpp/mrc/include/mrc/node/source_properties.hpp
- cpp/mrc/src/tests/segments/common_segments.cpp
- cpp/mrc/src/tests/test_pipeline.cpp
- cpp/mrc/tests/test_edges.cpp
- python/mrc/_pymrc/include/pymrc/node.hpp
- python/mrc/_pymrc/src/segment.cpp
- python/mrc/tests/test_edges.cpp
- python/tests/test_edges.py
Previously, we supported `source->node->[nothing]` where a source object didnt have any downstream sinks to write to. In that situation, the object was just discarded on writing. This fixes the edge functionality to replicate the previous system.
> Add handling for empty downstream sources

- CMakeLists.txt
Clang will complain about deprecated flags if you pass fcoroutines to 16 or higher; this handles both cases and avoids warning spam.
> Update CMake to only add fcoroutines flag if clang version is less than 16 + bump to latest utils

- .github/workflows/ci_pipe.yml
- .github/workflows/pull_request.yml
- ci/scripts/github/build.sh
- ci/scripts/github/common.sh
This PR updates the `sccache` configuration settings to use a new bucket, `rapids-sccache-east`.
Unlike the previous `rapids-sccache` bucket, `rapids-sccache-east` resides in the same AWS region as the rest of our CI infrastructure (`us-east-2`).
This should result in faster, more reliable `sccache` connections and will also help keep our data transfer costs down.
**Important Note**: The changes from [this `sccache` PR](https://github.com/mozilla/sccache/pull/1403) are required to use a bucket in `us-east-2`. These changes were incorporated in `sccache` `v0.3.2`, so you'll need that version or later (preferably the latest, `v0.3.3`). Please ensure that your CI images satisfy this constraint before merging this PR.
Additionally, this PR updates the `SCCACHE_REGION` to the region of the …
> Update `sccache` bucket

- .github/workflows/ci_pipe.yml
- .github/workflows/pull_request.yml
This PR is using the AWS OIDC to get AWS credentials ([doc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)). Currently we are using permanent tokens that we need to manually rotate every 90 days. This PR is removing this requirement.
The `AWS_ROLE_ARN` and `AWS_REGION` are orgs variables defined here: https://github.com/organizations/nv-morpheus/settings/variables/actions.
> Use AWS OIDC to get AWS creds

- .github/workflows/ci_pipe.yml
Increasing the AWS credentials lifetime from 1h to 12h
> Set AWS credentials lifetime to 12h

- .github/workflows/ci_pipe.yml
- .github/workflows/pull_request.yml
This PR is a continuation of #294.
Omitting the other keys in the `permissions` block sets them to `none` ([src](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview)).
This is probably not a concern for `nv-morpheus`, but it caused issues for some private RAPIDS repositories so I wanted to update the `nv-morpheus` repos for consistency.
To remedy this, this PR includes the following changes:
- Keeps the `id-token` permission as `write`, but sets the remaining permissions as described in the `restricted` column [here](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
- Also sets `pull_request` to `read` so that `fetch_base_branch` in `common.sh` can use it
- Moves the `permissions` blocks to …
> Update workflow `permissions` block

- cpp/mrc/include/mrc/utils/macros.hpp
- cpp/mrc/tests/CMakeLists.txt
- cpp/mrc/tests/test_macros.cpp
In debug it uses a dynamic cast and asserts not null, in release it uses a static cast.
In Morpheus I have a bunch of code that looks like:
```
DCHECK(std::dynamic_pointer_cast<morpheus::InferenceMemory>(self.memory) != nullptr);
return std::static_pointer_cast<morpheus::InferenceMemory>(self.memory);
```
This would allow for:
```
return MRC_PTR_CAST(morpheus::InferenceMemory, self.memory);
```
Related to: https://github.com/nv-morpheus/Morpheus/issues/735
> Pointer cast macro

- cpp/mrc/include/mrc/forward.hpp
- cpp/mrc/include/mrc/types.hpp
* Remove forward declares for classes that no longer exist, or no longer exist in the top-level `mrc` namespace.
* Remove duplicate entries.
* Forward-declare structs as structs.
* Fix casing of `CpuSet` & `NumaSet` structs.
* Remove unused type-aliases from `types.hpp`, this could be a potentially breaking change if any users were using these types.
fixes #291
> Cleanup top-level forward.hpp and types.hpp

- .gitmodules
- CMakeLists.txt
- docs/quickstart/CMakeLists.txt
- docs/quickstart/compile.sh
- docs/quickstart/environment_cpp.yml
- docs/quickstart/hybrid/mrc_qs_hybrid/common/CMakeLists.txt
- docs/quickstart/hybrid/mrc_qs_hybrid/ex00_wrap_data_objects/CMakeLists.txt
- docs/quickstart/hybrid/mrc_qs_hybrid/ex01_wrap_nodes/CMakeLists.txt
- python/CMakeLists.txt
- python/mrc/_pymrc/CMakeLists.txt
- python/mrc/_pymrc/tests/CMakeLists.txt
This is the corresponding update to incorporate changes from https://github.com/nv-morpheus/utilities/pull/17.
Mainly this reorganizes the python CMake checks so they only get executed once. Significantly speeding up the configure step.
> Improvements to the python module generation CMake code

- .github/workflows/ci_pipe.yml
This PR is updating the runner labels to use ARC V2 self-hosted runners for CPU jobs only. This is needed to resolve the auto-scalling issues.
> Use ARC V2 self-hosted runners for CPU jobs

- .github/workflows/ci_pipe.yml
- .github/workflows/pull_request.yml
- ci/scripts/github/build.sh
- ci/scripts/github/conda.sh
* Use newly built CI images with CUDA 11.8
* Use the version of gcov installed via conda
> Use newly built CI images with CUDA 11.8

- .github/workflows/ci_pipe.yml
- .github/workflows/pull_request.yml
- Dockerfile
- cpp/mrc/CMakeLists.txt
- cpp/mrc/src/internal/system/device_info.cpp
- cpp/mrc/src/internal/system/device_info.hpp
- cpp/mrc/src/internal/system/topology.cpp
- cpp/mrc/src/tests/test_topology.cpp
Currently, we install the driver into one of the CI images to allow for stub generation during compilation. This was needed because `device_info.cpp` linked directly against `CUDA::nvml`. This caused a link dependency on a driver library which is problematic when building with CPU-only docker images.
Instead, we dynamically load `libnvidia-ml.so.1` (appending the `.so.1` to avoid collisions with the stub file `libnvidia-ml.so`) and the necessary functions at runtime. If the library is not found, using a GPU will be disabled. This allows loading of the library for stub generation without needing a GPU.
> Dynamically loading `libnvidia-ml.so.1` instead of directly linking

- .github/workflows/ci_pipe.yml
This PR is updating the runner labels to use ARC V2 self-hosted runners for GPU jobs. This is needed to resolve the auto-scalling issues.
> Use ARC V2 self-hosted runners for GPU jobs

- cpp/mrc/include/mrc/node/rx_node.hpp
- cpp/mrc/src/public/runnable/runner.cpp
This allows any thrown exceptions to be handled by the runner.
> RxNodeComponent should set exceptions on the context

- cpp/mrc/include/mrc/node/rx_node.hpp
- cpp/mrc/src/public/runnable/runner.cpp
- cpp/mrc/tests/test_edges.cpp
- cpp/mrc/tests/test_node.cpp
> Release an RxNodeComponent edge on error

- cpp/mrc/src/internal/control_plane/server.cpp
- cpp/mrc/src/internal/control_plane/server/subscription_manager.hpp
- cpp/mrc/src/internal/control_plane/server/tagged_issuer.hpp
* Replace references to `TaggedManager` with `TaggedIssuer`
* Ran across these while reading up on control plane
> Fix a few minor type-o's in comments

- cpp/mrc/src/public/modules/plugins.cpp
- cpp/mrc/tests/modules/test_module_registry.cpp
This PR removes all references to `boost::filesystem` in favor of `std::filesystem`. The std library should be preferred over the boost version
> Remove `boost::filesystem`

- cpp/mrc/include/mrc/coroutines/ring_buffer.hpp
- cpp/mrc/tests/coroutines/test_ring_buffer.cpp
Compiling on GCC 11.3 breaks due to this compiler bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103871. Using the workaround in [this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103871#c10) comment seems to fix the issue.
Tested on 11.3 locally. Changes should be benign. No way to test this in CI without adding GCC 11.3 to the build matrix.
> Workaround GCC 11.3 compiler bug

- ci/conda/recipes/run_conda_build.sh
- cpp/mrc/include/mrc/memory/resources/arena_resource.hpp
- cpp/mrc/include/mrc/memory/resources/detail/arena.hpp
The conda build failed on the RMM 23.02 variant as shown [here](https://github.com/nv-morpheus/MRC/actions/runs/5481558555/jobs/9986229915) due to the change with moving `RMM_LOGGING_ASSERT` between versions 23.02 and 23.04.
This fix removes uses of `RMM_LOGGING_ASSERT` replacing it with the equivalent `DCHECK` which is used throughout the rest of the repo.
> Fix the conda build with RMM 23.02

- .github/workflows/ci_pipe.yml
- .github/workflows/pull_request.yml
- ci/scripts/github/conda.sh
This PR is testing the ability to enable/disable CI steps via labels on a PR. Uses the new action `rapidsai/shared-action-workflows/get-pr-info`
New label is `conda-build`.
> Adding option to configure running the conda-build CI step with labels

- .github/workflows/pull_request.yml
* No code changes other than updating the CI versions
fixes #350
> New CI images with rapids 23.06

- ci/conda/environments/dev_env.yml
- ci/conda/recipes/libmrc/conda_build_config.yaml
- ci/conda/recipes/libmrc/meta.yaml
closes https://github.com/nv-morpheus/MRC/issues/352
> Use libgrpc=1.54

- .github/workflows/ci_pipe.yml
- .github/workflows/pull_request.yml
Actions running after a PR is merged are broken due to the Prepare step assuming there is a PR. This fixes the prepare step to work with and without a PR
> Fixing actions running on non-PR branches

- ci/release/update-version.sh
Cherry picks some changes from https://github.com/nv-morpheus/MRC/pull/361 to allow other PRs to run CI since that PR is marked as `DO_NOT_MERGE`
> Fixing an issue with `update-versions.sh` which always blocked CI

- CMakeLists.txt
- dependencies.yaml
- python/mrc/_pymrc/CMakeLists.txt
Adds a new `dependencies.yaml` which is used in RAPIDS devcontainer utils to generate conda env yamls, `project.toml`'s, and `setup.py`s on-the-fly using https://github.com/rapidsai/dependency-file-generator. Eventually we can generate/verify our existing environment files this way, but for now this gets us up and running in a RAPIDS devcontainer.
Also changes `prometheus-cpp::core` to a `PRIVATE`ly linked library, as it's not longer necessary to be `PUBLIC`, and otherwise breaks a combined MRC/Morpheus build.
Also adds a `MRC_PYTHON_INPLACE_BUILD` cmake option, which enables pybind11 modules to be copied back to the source tree.
MRC/Morpheus unified build environment is a WIP, but available here: https://github.com/cwharris/cyber-dev.
Contributes to …
> Updates for MRC/Morpheus to build in the same RAPIDS devcontainer environment

- docs/quickstart/python/mrc_qs_python/ex02_reactive_operators/README.md
Replace usage of deprecated `make_node_full` with `make_node` in the Quick Start Guide. Also fix a typo.
Contributes to https://github.com/nv-morpheus/Morpheus/issues/782.
> Make Quick Start Guide not use `make_node_full`

- ci/conda/environments/clang_env.yml
- ci/conda/environments/dev_env.yml
> Revert boost upgrade, and update clang to v16

- cpp/mrc/include/mrc/edge/edge_holder.hpp
- cpp/mrc/tests/test_edges.cpp
* Prevents `check_active_connection` from mistakenly returning true for a holder where `init_owned_edge` has been called but neither the `init_connected_edge method` or the `add_connector` method have not been called.
Relates to issue #360
> Fix EdgeHolder from incorrectly reporting an active connection

- ci/conda/recipes/libmrc/conda_build_config.yaml
PR #391 updated the version of boost, but I forgot to update the version in the package's yaml.
> Update boost versions to match version used in dev env

- ci/conda/environments/dev_env.yml
- python/mrc/_pymrc/CMakeLists.txt
- python/mrc/_pymrc/include/pymrc/coro.hpp
- python/mrc/_pymrc/src/coro.cpp
- python/mrc/_pymrc/tests/CMakeLists.txt
- python/mrc/_pymrc/tests/coro/CMakeLists.txt
- python/mrc/_pymrc/tests/coro/module.cpp
- python/mrc/core/CMakeLists.txt
- python/mrc/core/coro.cpp
- python/tests/test_coro.py
- python/tests/test_pycoro.py
Moves pycoro from Morpheus to MRC and incorperates tests from https://github.com/nv-morpheus/Morpheus/pull/1286
Closes https://github.com/nv-morpheus/Morpheus/issues/1268
> Move Pycoro from Morpheus to MRC

- python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
Closes https://github.com/nv-morpheus/Morpheus/issues/1339
Replaces the ClosableRingBuffer usage in AsyncioRunnable to instead use a traditional semaphore which seems to be more reliable for this use case.
> Use a traditional semaphore in AsyncioRunnable

- CHANGELOG.md
- ci/conda/environments/dev_env.yml
- python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
- python/mrc/_pymrc/include/pymrc/coro.hpp
- python/mrc/_pymrc/include/pymrc/utilities/function_wrappers.hpp
- python/mrc/_pymrc/src/executor.cpp
- python/mrc/_pymrc/src/module_registry.cpp
- python/mrc/_pymrc/src/module_wrappers/pickle.cpp
- python/mrc/_pymrc/src/module_wrappers/shared_memory.cpp
- python/mrc/_pymrc/src/segment.cpp
- python/mrc/_pymrc/src/subscriber.cpp
- python/mrc/_pymrc/src/utilities/object_cache.cpp
- python/mrc/_pymrc/src/watchers.cpp
- python/mrc/_pymrc/tests/test_asyncio_runnable.cpp
- python/mrc/_pymrc/tests/test_executor.cpp
- python/mrc/_pymrc/tests/test_pipeline.cpp
- python/mrc/_pymrc/tests/test_serializers.cpp
- python/mrc/_pymrc/tests/test_utils.cpp
- python/mrc/benchmarking/watchers.cpp
- python/mrc/core/common.cpp
- python/mrc/core/coro.cpp
- python/mrc/core/operators.cpp
- python/mrc/core/pipeline.cpp
- python/mrc/core/segment.cpp
- python/mrc/core/segment/module_definitions/mirror_tap_orchestrator.cpp
- python/mrc/core/segment/module_definitions/segment_module_registry.cpp
- python/mrc/core/segment/module_definitions/segment_modules.cpp
- python/mrc/core/subscriber.cpp
- python/mrc/tests/sample_modules.cpp
- python/mrc/tests/test_edges.cpp
Forward-merge triggered by push to `branch-23.11` that creates a PR to keep `branch-24.03` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.11 to branch-24.03

- mrc.code-workspace
Removes the deprecated python settings in favor of the options recommended in https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions
> Updating the workspace settings to remove deprecated python options

- .github/workflows/pr.yaml
- mrc.code-workspace
* Adds a new `has_skip_ci_label` output to the `prepare` job.
* Skips the rest of the pipeline when true
> Optionally skip the CI pipeline if the PR contains the skip-ci label

- .github/workflows/ci_pipe.yml
- Dockerfile
- python/MANIFEST.in
- python/setup.py
* Prevent `libmrc_pymrc.so` from being installed into python's site-packages dir, as this lib is already present in the lib dir.
* Fixes permissions issue where the conda env was owned by `root:root`, simply ensuring the env retains the `conda` group permission wasn't sufficient as `cmake` attempts to modify exiting dirs (https://gitlab.kitware.com/cmake/cmake/-/issues/10978), and running `chmod -R` after the fact is too slow.
Closes #428
> Remove redundant copy of libmrc_pymrc.so

- .github/workflows/ci_pipe.yml
- cmake/dependencies.cmake
- cpp/mrc/CMakeLists.txt
- docs/quickstart/hybrid/mrc_qs_hybrid/ex00_wrap_data_objects/CMakeLists.txt
- docs/quickstart/hybrid/mrc_qs_hybrid/ex01_wrap_nodes/CMakeLists.txt
- protos/CMakeLists.txt
- python/mrc/_pymrc/CMakeLists.txt
This PR fixes an issue where some libraries were using `${PROJECT_NAME}-core-exports` and others were using `${PROJECT_NAME}-exports`. Since there is no need for multiple export sets anymore, this updates all exports to be `${PROJECT_NAME}-exports`
Requires https://github.com/nv-morpheus/utilities/pull/61 to be merged first
> Unifying cmake exports name across all Morpheus repos

- ci/conda/recipes/run_conda_build.sh
- conda/environments/all_cuda-121_arch-x86_64.yaml
- conda/environments/ci_cuda-121_arch-x86_64.yaml
- dependencies.yaml
Closes https://github.com/nv-morpheus/MRC/issues/435
Closes https://github.com/nv-morpheus/MRC/issues/424
Closes https://github.com/nv-morpheus/MRC/issues/423
Closes https://github.com/nv-morpheus/MRC/issues/422
> Update Conda channels to prioritize `conda-forge` over `nvidia`

- python/mrc/_pymrc/include/pymrc/utils.hpp
- python/mrc/_pymrc/src/utils.cpp
- python/mrc/_pymrc/tests/test_utils.cpp
* Currently when `cast_from_pyobject` encounters an unsupported type it returns a json null.
* Updates the method to throw a `pybind11::type_error`, matching the `TypeError` exception raised by the Python std `json.dumps` method.
* Add `get_py_type_name` helper method
* Breaking behavior change
Closes #450
> Update cast_from_pyobject to throw on unsupported types rather than returning null

- python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
When running an instance of the `AsyncioRunnable` class, it populates the output with:
```
I20240313 16:41:26.300143 3296734 asyncio_runnable.hpp:246] AsyncioRunnable::run() > Creating new event loop
I20240313 16:41:26.300436 3296734 asyncio_runnable.hpp:259] AsyncioRunnable::run() > Calling run_until_complete() on main_task()
```
This PR changes that to a `DVLOG(10)` since this information is more tracing than actually informative.
> Removing the INFO log when creating an AsyncioRunnable

- cmake/Configure_UCXX.cmake
- cpp/mrc/src/internal/data_plane/data_plane_resources.cpp
- cpp/mrc/src/internal/data_plane/data_plane_resources.hpp
- cpp/mrc/src/public/runtime/remote_descriptor.cpp
- cpp/mrc/src/tests/test_network.cpp
Allow memory pressure control in`DataPlaneResources2` via a maximum number of remote descriptors registered and add multithreaded test to verify completion despite blocking behavior of registration thread.
> Allow memory pressure control in`DataPlaneResources2`

- ci/conda/recipes/libmrc/meta.yaml
- ci/iwyu/mappings.imp
- conda/environments/all_cuda-121_arch-x86_64.yaml
- conda/environments/ci_cuda-121_arch-x86_64.yaml
- dependencies.yaml
- python/mrc/_pymrc/CMakeLists.txt
- python/mrc/_pymrc/include/pymrc/types.hpp
- python/mrc/_pymrc/include/pymrc/utilities/json_values.hpp
- python/mrc/_pymrc/include/pymrc/utilities/object_cache.hpp
- python/mrc/_pymrc/include/pymrc/utils.hpp
- python/mrc/_pymrc/src/utilities/json_values.cpp
- python/mrc/_pymrc/src/utils.cpp
- python/mrc/_pymrc/tests/CMakeLists.txt
- python/mrc/_pymrc/tests/test_json_values.cpp
- python/mrc/_pymrc/tests/test_utils.cpp
* Add an optional `unserializable_handler_fn` callback to `mrc::pymrc::cast_from_pyobject` which will be invoked for any unsupported Python object. Allowing for serializing unsupported object.
ex:
```cpp
pymrc::unserializable_handler_fn_t handler_fn = [](const py::object& source,
const std::string& path) {
return nlohmann::json(py::cast<float>(source));
};
// decimal.Decimal is not serializable
py::object Decimal = py::module_::import("decimal").attr("Decimal");
py::object o       = Decimal("1.0");
EXPECT_EQ(pymrc::cast_from_pyobject(o, handler_fn), nlohmann::json(1.0));
```
* Add `JSONValues` container class which is an immutable container for holding Python values as `nlohmann::json` objects if possible, and as `pybind11::object` otherwise. The container can be copied and moved, but the …
> Add JSONValues container for holding Python values as JSON objects if possible, and as pybind11::object otherwise

- python/mrc/_pymrc/include/pymrc/utilities/json_values.hpp
- python/mrc/_pymrc/tests/test_json_values.cpp
- python/mrc/tests/utils.cpp
- python/tests/test_json_values_cast.py
* Add pybind11 type-caster for `JSONValues`
> Add pybind11 type caster for JSONValues

- ci/conda/recipes/libmrc/meta.yaml
- ci/iwyu/mappings.imp
- conda/environments/all_cuda-121_arch-x86_64.yaml
- conda/environments/ci_cuda-121_arch-x86_64.yaml
- cpp/mrc/CMakeLists.txt
- cpp/mrc/include/mrc/coroutines/task_container.hpp
- cpp/mrc/include/mrc/coroutines/test_scheduler.hpp
- cpp/mrc/src/public/coroutines/task_container.cpp
- cpp/mrc/src/public/coroutines/test_scheduler.cpp
- cpp/mrc/tests/coroutines/test_task_container.cpp
- dependencies.yaml
- python/mrc/_pymrc/CMakeLists.txt
- python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
- python/mrc/_pymrc/include/pymrc/types.hpp
- python/mrc/_pymrc/include/pymrc/utilities/json_values.hpp
- python/mrc/_pymrc/include/pymrc/utilities/object_cache.hpp
- python/mrc/_pymrc/include/pymrc/utils.hpp
- python/mrc/_pymrc/src/utilities/json_values.cpp
- python/mrc/_pymrc/src/utils.cpp
- python/mrc/_pymrc/tests/CMakeLists.txt
- python/mrc/_pymrc/tests/test_json_values.cpp
- python/mrc/_pymrc/tests/test_utils.cpp
Adds maximum simultaneous tasks support to `TaskContainer` by only starting new tasks if the number of currently executing tasks is less than the maximum number of simultaneous tasks and starting new tasks as older tasks shut down. this eliminates the need for external semaphores or ticketing systems.
> Add maximum simultaneous tasks support to `TaskContainer`

- conda/environments/all_cuda-121_arch-x86_64.yaml
- conda/environments/ci_cuda-121_arch-x86_64.yaml
- dependencies.yaml
Morpheus documentation won't build with doxygen 1.10.0, but we need MRC and Morpheus doxygen versions to match so cross-repository environments can be solved correctly. This PR downgrades doxygen to the version used by Morpheus.
> Downgrade doxygen to match Morpheus

- ci/iwyu/mappings.imp
- cpp/mrc/CMakeLists.txt
- cpp/mrc/include/mrc/utils/string_utils.hpp
- cpp/mrc/src/internal/utils/parse_config.cpp
- cpp/mrc/src/internal/utils/parse_ints.cpp
- cpp/mrc/src/public/utils/string_utils.cpp
- cpp/mrc/tests/CMakeLists.txt
- cpp/mrc/tests/test_string_utils.cpp
- python/mrc/_pymrc/include/pymrc/utilities/json_values.hpp
- python/mrc/_pymrc/src/utilities/json_values.cpp
* All three methods performed nearly identical operations, but were defined in anonymous namespaces and not exposed in a header preventing sharing.
* Consolidate all three into a new `split_string_to_vector` in `string_utils.hpp`
closes #454
> Consolidate redundant split_string_to_array, split_string_on & split_path methods

- .github/workflows/pr.yaml
- CHANGELOG.md
- README.md
- cpp/mrc/benchmarks/bench_baselines.cpp
- cpp/mrc/include/mrc/coroutines/task_container.hpp
- cpp/mrc/include/mrc/coroutines/test_scheduler.hpp
- cpp/mrc/src/public/coroutines/task_container.cpp
- cpp/mrc/src/public/coroutines/test_scheduler.cpp
- cpp/mrc/tests/coroutines/test_task_container.cpp
- python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
* Manual PR resolving merge conflicts from PR #468
> Forward-merge branch-24.03 into branch-24.06

- ci/scripts/cpp_checks.sh
- python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
* Adds `AutoRegSinkAdapter` and `AutoRegEgressPort` to `AsyncSink`
* Adds `AutoRegSourceAdapter` and `AutoRegIngressPort` to `AsyncSource`
* Giving `AsyncSink`, `AsyncSource` and `AsyncioRunnable` the same implicit converter functionality that `PythonNode` has
* Fixes unrelated CI issue for IWYU, since IWYU can only run on compilation units, we can't execute it when a change only includes header files.
Closes nv-morpheus/Morpheus#1626
> Add auto register helpers to AsyncSink and AsyncSource

- .pre-commit-config.yaml
- ci/check_style.sh
Contributes to https://github.com/rapidsai/dependency-file-generator/issues/89.
`--file_key` has been deprecated in `rapids-dependency-file-generator` for a few months, and I'm looking to fully remove it.
This PR proposes:
* switching this project's uses from `--file_key` to `--file-key`
* updating the version of `rapids-dependency-file-generator` used in `pre-commit` to its latest release
* switching from `mamba env create --force` to `mamba env create --yes`
> resolve rapids-dependency-file-generator warning

- cpp/mrc/src/internal/service.hpp
- python/mrc/_pymrc/src/segment.cpp
* When a Python generator source yields a value, and the subscriber is no longer subscribed, stop the source.
* Fix out of date docstring comment.
This is a partial fix for nv-morpheus/Morpheus#1838
> Stop a python source once the subscriber is no longer subscribed

- python/mrc/_pymrc/include/pymrc/segment.hpp
- python/mrc/_pymrc/src/segment.cpp
- python/mrc/core/segment.cpp
- python/tests/conftest.py
- python/tests/test_executor.py
* Allows a Python generator source to check if the subscriber is still subscribed.
* Define a class `SubscriberFuncWrapper`  for Python sources rather than just a lambda. The reason is that python objects captured by the lambda need to be destroyed while the gil is held, which causes a problem if the lambda is destroyed unexpectedly.
* Update `conftest.py` to set the loglevel to `DEBUG` if the `GLOG_v` environment variable is defined.
> Define a Python source which receives a reference to a subscriber

- cpp/mrc/src/internal/system/device_info.cpp
* Since CPU-only mode will become a supported feature we want to avoid unnecessary warnings.
Relates to nv-morpheus/Morpheus#1851
> Change `LOG(WARNING)` to `VLOG(1)` when no GPUs are detected

- python/mrc/_pymrc/include/pymrc/segment.hpp
- python/mrc/_pymrc/include/pymrc/subscriber.hpp
- python/mrc/_pymrc/src/segment.cpp
- python/mrc/_pymrc/src/subscriber.cpp
- python/mrc/core/segment.cpp
- python/mrc/core/subscriber.cpp
- python/tests/test_executor.py
- python/tests/test_node.py
* Remove the `make_source_subscriber` method in favor of inspecting the Python function signature.
* Since the `make_source_subscriber` method was never part of a release I think this can still be considered a non-breaking change.
> Pass a `mrc.Subscription` object to sources rather than a `mrc.Subscriber`

- cpp/mrc/src/internal/system/partitions.cpp
If the NUMA node check fails for a GPU, the entire pipeline cannot start. This allows setting `MRC_SKIP_NUMA_CHECK=1` to bypass the assertion if the check fails.
Closes #504
> Adding environment variable to allow skip NUMA node check

- python/mrc/_pymrc/include/pymrc/coro.hpp
- python/mrc/core/coro.cpp
- python/mrc/core/executor.cpp
* Include MRC libs with quotes not <>
* Add MRC version string to coro module (all the other Python modules have this)
* Fix spelling mistake in a comment in `python/mrc/core/executor.cpp`
Closes [#492](https://github.com/nv-morpheus/MRC/issues/492)
> Fix Incorrect docstring in `mrc.core.coro`

- .devcontainer/conda/Dockerfile
- .devcontainer/conda/devcontainer.json
- .devcontainer/opt/mrc/conda/Dockerfile
- .devcontainer/opt/mrc/conda/devcontainer.json
This PR is replacing the `VAULT_HOST` variable with `AWS_ROLE_ARN`. This is required to use the new token service to get AWS credentials
> devcontainer: replace VAULT_HOST with AWS_ROLE_ARN

- ci/conda/README.md
- ci/conda/recipes/libmrc/move_libmrc_files.sh
- ci/conda/recipes/libmrc/move_mrc_files.sh
- cpp/mrc/CMakeLists.txt
- protos/CMakeLists.txt
- python/CMakeLists.txt
- python/mrc/_pymrc/CMakeLists.txt
- python/mrc/_pymrc/tests/CMakeLists.txt
Fixes a few issues:
- Headers were being installed incorrectly with new `HEADER_SET`
- Fixed packages for pymrc component
- Standardized the component naming
Closes #509
> Fix CMake issue which installed headers incorrectly during conda build

- cpp/mrc/include/mrc/core/concepts/not_void.hpp
- cpp/mrc/include/mrc/coroutines/concepts/awaitable.hpp
- cpp/mrc/tests/test_node.cpp
* Clean up concept definitions
* Fix ParallelTests/NodeMultiThread bug
> Chore: improve concept definitions

- cpp/mrc/include/mrc/edge/edge_channel.hpp
- cpp/mrc/include/mrc/edge/edge_readable.hpp
- cpp/mrc/include/mrc/node/sink_properties.hpp
- cpp/mrc/include/mrc/node/source_properties.hpp
- cpp/mrc/tests/node/test_nodes.hpp
- python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
- python/mrc/_pymrc/include/pymrc/node.hpp
- python/mrc/_pymrc/tests/test_asyncio_runnable.cpp
* Fixes a bug first observed in [NVIDIA-AI-Blueprints/vulnerability-analysis](https://github.com/NVIDIA-AI-Blueprints/vulnerability-analysis) and reported in nv-morpheus/Morpheus#2086
* `AsyncioRunnable` will now call `on_state_update(state_t::Kill)` when an exception is caught
* Replace blocking call to `await_read` with `await_read_until` allowing `AsyncioRunnable` to check `stop_source.stop_requested()` 
* Define new `await_read_until` method in `IEdgeReadable`, unfortunately this interface has numerous subclasses which all then needed new `await_read_until` methods, even though `EdgeChannelReader` is the only class that really needed it. Alternatives:
- In `AsyncSink` perform a static cast of `this->get_readable_edge()` to `EdgeChannelReader`
- Define `await_read_until` method in …
> Fix bug where `AsyncioRunnable` hangs if `process_one` throws and the source is not emitting new values

- CMakeLists.txt
- CMakePresets.json
1. Currently, CMake adds `-L` flags to compiling object files. GCC does not warn about this, but Clang does. Suppress the noise with `-Wno-unused-command-line-argument`.
2. `CMakePresets.json` are relatively recent but allow you to easily kick off a CMake configure/build/test (or combination of all via workflow). Add an initial (opinionated) configuration that offers four options:
* gcc-debug
* gcc-release
* clang-debug
* clang-release
The advantage here is the end user doesn't have to remember a bunch of flags to pass to CMake. They can just invoke via: `cmake --workflow --preset gcc-debug`. This also offers better IDE integration, particularly in VSCode.
> [chore] Suppress innocent warning with clang; add simple CMakePresets.json

- cpp/mrc/src/public/coroutines/io_scheduler.cpp
- cpp/mrc/tests/coroutines/test_io_scheduler.cpp
This PR simplifies the implementation of `yield_for` and `yield_until` while also eliminating a bug in `yield_for` which can cause it to prematurely notify.
Closes #532
> Bugfix: Fix IoScheduler::yield_until and improve tests

- ci/scripts/github/test.sh
- ci/scripts/github/test_codecov.sh
> Disable the test_mrc_benchmarking set of tests in CI
